{% set name = "optax" %}
{% set version = "0.1.4" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/optax-{{ version }}.tar.gz
  sha256: fb7a0550d57a6636164a3de25986a8a19be8ff6431fcdf1225b4e05175810f22

build:
  number: 0
  skip: True  # [py<36]
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python
    - pip
    - setuptools
    - wheel
  run:
    - python
    - absl-py >=0.7.1
    - chex >=0.1.5
    - jax >=0.1.55
    - jaxlib >=0.1.37
    - numpy >=1.18.0
    - typing_extensions >=3.10

test:
  imports:
    - optax
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/deepmind/optax
  summary: A gradient processing and optimisation library in JAX.
  description: |
    Optax is a gradient processing and optimization library for JAX.

    Optax is designed to facilitate research by providing building blocks that can be easily recombined in custom ways.

    The goals are to:
      - Provide simple, well-tested, efficient implementations of core components.
      - Improve research productivity by enabling to easily combine low level ingredients into custom optimisers (or other gradient processing components).
      - Accelerate adoption of new ideas by making it easy for anyone to contribute.
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE

extra:
  recipe-maintainers:
    - PhilipVinc
    - hbq1
