{% set name = "optax" %}
{% set version = "0.0.8" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/optax-{{ version }}.tar.gz
  sha256: fae89d32d591e1f2319f439666266615696d1912e143c7f8029640d09654fc07

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - absl-py >=0.7.1
    - chex >=0.0.4
    - jax >=0.1.55
    - jaxlib >=0.1.37
    - numpy >=1.18.0

test:
  imports:
    - optax
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/deepmind/optax
  summary: A gradient processing and optimisation library in JAX.
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - PhilipVinc
    - hbq1
