{% set name = "optax" %}
{% set version = "0.2.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 5b225b35066fc3eebaa4d798f1b4173b4d57d1a480610908981f8343b50af0b0

build:
  number: 0
  # jax >=0.5.3 is not available for the py<311
  skip: true  # [py<311]
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python
    - pip
    - flit-core >=3.2,<4
  run:
    - python
    - absl-py >=0.7.1
    - jax >=0.5.3
    - jaxlib >=0.5.3
    - numpy >=1.18.0

test:
  source_files:
    - optax/optax_test.py
  imports:
    - optax
    - optax._src
    - optax._src.alias
    - optax._src.base
    - optax._src.deprecations
    - optax._src.factorized
    - optax._src.linear_algebra
    - optax._src.linesearch
    - optax._src.lookahead
    - optax._src.numerics
    - optax._src.transform
    - optax._src.update
    - optax._src.utils
    - optax.assignment._hungarian_algorithm
    - optax.contrib
    - optax.contrib._acprop
    - optax.contrib._ademamix
    - optax.contrib._adopt
    - optax.contrib._cocob
    - optax.contrib._complex_valued
    - optax.contrib._dadapt_adamw
    - optax.contrib._dog
    - optax.contrib._galore
    - optax.contrib._madgrad
    - optax.contrib._mechanic
    - optax.contrib._momo
    - optax.contrib._muon
    - optax.contrib._privacy
    - optax.contrib._prodigy
    - optax.contrib._reduce_on_plateau
    - optax.contrib._sam
    - optax.contrib._schedule_free
    - optax.contrib._sophia
    - optax.experimental
    - optax.losses
    - optax.losses._classification
    - optax.losses._fenchel_young
    - optax.losses._ranking
    - optax.losses._regression
    - optax.losses._segmentation
    - optax.losses._self_supervised
    - optax.losses._smoothing
    - optax.microbatching._microbatching
    - optax.perturbations
    - optax.perturbations._make_pert
    - optax.projections._projections
    - optax.schedules
    - optax.schedules._inject
    - optax.schedules._join
    - optax.schedules._schedule
    - optax.second_order._deprecated
    - optax.transforms
    - optax.transforms._accumulation
    - optax.transforms._adding
    - optax.transforms._clipping
    - optax.transforms._combining
    - optax.transforms._conditionality
    - optax.transforms._constraining
    - optax.transforms._freezing
    - optax.transforms._layouts
    - optax.transforms._masking
    - optax.transforms._monitoring
    - optax.tree
    - optax.tree_utils
    - optax.tree_utils._casting
    - optax.tree_utils._random
    - optax.tree_utils._state_utils
    - optax.tree_utils._tree_math
  commands:
    - pip check
    - python -c "from importlib.metadata import version; assert(version('{{ name }}')=='{{ version }}')"
    - pytest -v optax/optax_test.py
  requires:
    - pip
    - pytest

about:
  home: https://github.com/deepmind/optax
  summary: A gradient processing and optimisation library in JAX.
  description: |
    Optax is a gradient processing and optimization library for JAX.
    Optax is designed to facilitate research by providing building blocks that can be easily recombined in custom ways.
    The goals are to:
    - Provide simple, well-tested, efficient implementations of core components.
    - Improve research productivity by enabling to easily combine low level ingredients into custom optimisers (or other gradient processing components).
    - Accelerate adoption of new ideas by making it easy for anyone to contribute.
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  dev_url: https://github.com/deepmind/optax
  doc_url: https://optax.readthedocs.io

extra:
  recipe-maintainers:
    - PhilipVinc
    - hbq1
